apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: auto-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: http://host.minikube.internal:3000/gitadmin/infrastructure.git
        revision: HEAD
        directories:
          - path: applications/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: http://host.minikube.internal:3000/gitadmin/infrastructure.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
